<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Governance and accountability at Africa Innovation & Development Academy.">
  <link rel="icon" type="image/png" href="Logo.png">
  <title>Governance & Team | AIDA</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/style.css">
</head>
<body class="institution-page">
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="institution-header" id="top"><nav class="nav container" aria-label="Main navigation"><a class="brand" href="index.php" aria-label="AIDA home"><img src="Logo.png" alt="AIDA — Africa Innovation & Development Academy"></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links"><span></span><span></span><span></span><span class="sr-only">Open menu</span></button><div class="nav-links" id="nav-links"><a href="index.php#about">About us</a><a href="index.php#work">Our work</a><a class="active-link" href="governance.php">Governance</a><a href="index.php#contact" class="nav-cta">Partner with us <span>↗</span></a></div></nav></header>
  <main id="main">
    <section class="institution-hero"><div class="container"><p class="eyebrow"><span></span> TRUST, ACCOUNTABILITY &amp; STEWARDSHIP</p><div class="row align-items-end g-4"><div class="col-lg-8"><h1>Accountability is part of our <em>impact.</em></h1></div><div class="col-lg-4"><p>Strong governance helps AIDA remain independent in thought, responsible in practice and accountable to the communities and partners we serve.</p></div></div></div></section>
    <section class="section"><div class="container"><div class="intro-grid row g-5"><p class="section-kicker col-md-4">01 / OUR COMMITMENT</p><div class="col-md-8"><h2>Public purpose deserves <em>public trust.</em></h2><p class="lead">AIDA is building a culture of integrity, learning and transparent decision-making. Our governance arrangements are designed to protect our mission and strengthen the quality of our work.</p></div></div><div class="governance-principles row g-3 mt-5"><article class="col-md-6 col-xl-3"><span>01</span><h3>Independent judgement</h3><p>Our research and dialogue are guided by evidence and the public interest.</p></article><article class="col-md-6 col-xl-3"><span>02</span><h3>Responsible stewardship</h3><p>We aim to manage people, partnerships and resources with care.</p></article><article class="col-md-6 col-xl-3"><span>03</span><h3>Open learning</h3><p>We share what we learn, including the lessons that improve our practice.</p></article><article class="col-md-6 col-xl-3"><span>04</span><h3>Respect &amp; inclusion</h3><p>We create conditions for people to participate safely and meaningfully.</p></article></div></div></section>
    <section class="governance-structure"><div class="container"><p class="section-kicker light">02 / HOW WE ARE ORGANISED</p><h2>Clear roles. Shared <em>responsibility.</em></h2><div class="structure-flow"><article><span>01</span><h3>Governing body</h3><p>Provides strategic oversight, protects AIDA’s mission and monitors organisational performance.</p></article><i>↓</i><article><span>02</span><h3>Executive leadership</h3><p>Leads day-to-day strategy, delivery, partnerships and accountable management.</p></article><i>↓</i><article><span>03</span><h3>Research &amp; programmes</h3><p>Develops evidence, convenes dialogue and delivers initiatives with communities and partners.</p></article></div></div></section>
    <section class="section"><div class="container"><div class="policy-heading"><div><p class="section-kicker">03 / POLICIES &amp; DISCLOSURES</p><h2>How we hold ourselves <em>to account.</em></h2></div><p>As AIDA’s governance documents are formally approved, they will be published here for public access.</p></div><div class="policy-list"><a href="#contact"><span>01</span><b>Code of conduct</b><small>Coming soon</small><em>→</em></a><a href="#contact"><span>02</span><b>Safeguarding policy</b><small>Coming soon</small><em>→</em></a><a href="#contact"><span>03</span><b>Privacy &amp; data protection</b><small>Coming soon</small><em>→</em></a><a href="#contact"><span>04</span><b>Complaints &amp; feedback</b><small>Coming soon</small><em>→</em></a><a href="#contact"><span>05</span><b>Annual report &amp; accounts</b><small>Coming soon</small><em>→</em></a></div></div></section>
    <section class="team-callout"><div class="container"><p class="eyebrow"><span></span> OUR PEOPLE</p><h2>Meet the people who will shape <em>AIDA.</em></h2><p>Leadership, governing-body and team profiles will be published here once formal appointments are confirmed.</p><a class="button button-gold" href="index.php#contact">Contact AIDA <span>→</span></a></div></section>
  </main>
  <footer><div class="container footer-inner"><a class="footer-brand" href="index.php"><img src="Logo.png" alt="AIDA"></a><p>Research. Dialogue. Impact.</p><p>© <?= date('Y') ?> Africa Innovation &amp; Development Academy.</p><a href="#top">Back to top ↑</a></div></footer><script src="assets/js/main.js"></script>
</body></html>
