<?php
declare(strict_types=1);
if($section==='editor'){
    $item=['id'=>'','content_type'=>'insight','title'=>'','slug'=>'','summary'=>'','body'=>'','status'=>'draft','featured_image'=>'','document_path'=>'','video_url'=>'','event_date'=>'','authors'=>'','category'=>'','document_date'=>''];
    if(!empty($_GET['id'])){$item=array_replace($item,content_for_edit((int)$_GET['id']));$q=db()->prepare('SELECT * FROM content_metadata WHERE content_id=?');$q->execute([$item['id']]);$item=array_replace($item,$q->fetch()?:[]);}
    $q=db()->prepare('SELECT setting_value FROM site_settings WHERE setting_key=?');$q->execute(['homepage_content_'.(int)$item['id']]);$item['show_on_homepage']=$q->fetchColumn()==='1';
    $retry=$_SESSION['content_form']??null;unset($_SESSION['content_form']);if($retry && (int)$retry['id']===(int)$item['id'])$item=array_replace($item,$retry['values']);
    $q=db()->prepare('SELECT m.* FROM media m LEFT JOIN media_state s ON s.media_id=m.id WHERE s.deleted_at IS NULL'.($user['role']==='contributor'?' AND m.uploaded_by=?':'').' ORDER BY m.created_at DESC LIMIT 500');$q->execute($user['role']==='contributor'?[$user['id']]:[]);$library=$q->fetchAll();
    $attached=$item['id']?array_column(content_extra_documents((int)$item['id']),'id'):[];
    // Keep older attached files visible even when they fall outside the recent-file picker limit.
    $visible=array_column($library,'id');
    foreach(array_diff($attached,$visible) as $mid){$q=db()->prepare('SELECT * FROM media WHERE id=?');$q->execute([$mid]);$old=$q->fetch();if($old && ($user['role']!=='contributor' || (int)$old['uploaded_by']===(int)$user['id']))$library[]=$old;}
    admin_header($item['id']?'Edit content':'Create content','editor'); ?>
<form method="post" enctype="multipart/form-data" class="editor-form" data-upload-form data-max-bytes="<?=content_upload_limit()?>" data-post-bytes="<?=ini_bytes((string)ini_get('post_max_size'))?>">
<input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_content"><input type="hidden" name="id" value="<?=e((string)$item['id'])?>">
<div class="editor-grid"><div class="editor-main-fields"><label>Title<input name="title" maxlength="255" value="<?=e($item['title'])?>" required></label><label>Short summary<textarea name="summary" rows="3"><?=e($item['summary'])?></textarea></label><label>Write-up / content<textarea name="body" rows="16"><?=e($item['body'])?></textarea></label>
<section class="admin-card document-details"><h2>Publication details</h2><div class="form-grid"><label>Authors<input name="authors" maxlength="255" value="<?=e($item['authors'])?>" placeholder="Names as they should appear publicly"></label><label>Category / topic<input name="category" maxlength="120" value="<?=e($item['category'])?>" placeholder="e.g. Economic development"></label><label>Document date<input type="date" name="document_date" value="<?=e($item['document_date'])?>"></label></div></section>
<section class="admin-card"><h2>Additional documents</h2><p class="hint">Attach supporting reports, appendices or other documents. Uncheck an existing attachment to detach it; the original file stays in the library.</p>
<label class="upload-drop">Upload supporting documents<input type="file" name="additional_documents[]" accept=".pdf,.docx,.xlsx,.pptx" multiple><small>Select or drop up to 10 files.</small></label>
<label>Find existing documents<input type="search" data-filter-list="supporting-documents" placeholder="Search by filename"></label><div id="supporting-documents" class="attachment-checklist">
<?php foreach($library as $media):if(media_kind($media['mime_type'])!=='document')continue;?><label class="checkbox-label" data-search-item><input type="checkbox" name="document_ids[]" value="<?=$media['id']?>" <?=in_array($media['id'],$attached)?'checked':''?>><?=e($media['original_name'])?></label><?php endforeach;?>
</div></section></div><aside class="editor-side">
<label>Content type<select name="content_type"><?php foreach($types as $key=>$label):?><option value="<?=$key?>" <?=$item['content_type']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label>
<label>URL label<input name="slug" maxlength="255" value="<?=e($item['slug'])?>"><small>Leave blank to generate from title.</small></label>
<label>Status<select name="status"><?php foreach(($user['role']==='contributor'?['draft'=>'Draft','review'=>'Ready for review']:['draft'=>'Draft','review'=>'Ready for review','published'=>'Published','archived'=>'Archived']) as $key=>$label):?><option value="<?=$key?>" <?=$item['status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label>
<?php if($user['role']!=='contributor'):?><label class="checkbox-label"><input type="checkbox" name="show_on_homepage" value="1" <?=$item['show_on_homepage']?'checked':''?>>Show on homepage</label><p class="hint">Only published content appears publicly. Draft attachments require staff access.</p><?php endif;?>
<section class="attachment-panel"><h2>Main attachments</h2>
<?php foreach(['image'=>['Featured image','featured_image','.jpg,.jpeg,.png,.webp'],'document'=>['Main document','document_path','.pdf,.docx,.xlsx,.pptx'],'video'=>['Video file','video_url','.mp4,.webm']] as $kind=>[$label,$column,$accept]):?>
<label class="upload-drop"><?=e($label)?><input type="file" name="<?=$kind?>_file" accept="<?=$accept?>"><small>Select or drag a file here.</small></label>
<label>Or choose an existing <?=e($kind)?><input type="search" data-filter-select="<?=$kind?>-picker" placeholder="Find a file"><select id="<?=$kind?>-picker" name="<?=$kind?>_existing"><option value="">Keep current / no file selected</option><?php foreach($library as $media):if(media_kind($media['mime_type'])!==$kind)continue;?><option value="<?=$media['id']?>"><?=e($media['original_name'])?></option><?php endforeach;?></select></label>
<?php if($item[$column]):$currentUrl=media_url($item[$column]);?><a class="attachment-current" href="<?=e(preg_match('~^https?://~i',$currentUrl)?$currentUrl:'../'.$currentUrl)?>" target="_blank" rel="noopener">Open current <?=e($kind)?></a><label class="checkbox-label"><input type="checkbox" name="remove_<?=$kind?>" value="1">Detach current <?=e($kind)?></label><?php endif;?>
<?php endforeach;?>
<label>Or an external video link<input type="url" name="video_link" value="<?=e($item['video_link']??'')?>" placeholder="https://www.youtube.com/..."></label>
<p class="hint">Maximum <?=round(content_upload_limit()/1048576,1)?> MB per file; <?=e((string)ini_get('post_max_size'))?> combined server limit. File replacements can also be managed in Media &amp; Documents.</p>
</section><label>Event date<input type="datetime-local" name="event_date" value="<?=e($item['event_date']?date('Y-m-d\TH:i',strtotime($item['event_date'])):'')?>"></label>
<div class="upload-feedback" data-upload-feedback aria-live="polite"></div><progress data-upload-progress max="100" value="0" hidden></progress><button class="admin-button">Save content</button></aside></div></form>
<?php admin_footer();return;}

if($section==='media'){
    $search=mb_substr(trim((string)($_GET['q']??'')),0,120);$kind=$_GET['kind']??'';
    $sql='SELECT m.* FROM media m LEFT JOIN media_state s ON s.media_id=m.id WHERE s.deleted_at IS NULL';$params=[];
    if($user['role']==='contributor'){$sql.=' AND m.uploaded_by=?';$params[]=$user['id'];}
    if($search){$sql.=' AND (m.original_name LIKE ? OR m.alt_text LIKE ?)';$params[]='%'.$search.'%';$params[]='%'.$search.'%';}
    if(in_array($kind,['image','video'],true)){$sql.=' AND m.mime_type LIKE ?';$params[]=$kind.'/%';}elseif($kind==='document')$sql.=" AND m.mime_type NOT LIKE 'image/%' AND m.mime_type NOT LIKE 'video/%'";
    $q=db()->prepare($sql.' ORDER BY m.created_at DESC LIMIT 100');$q->execute($params);$library=$q->fetchAll();admin_header('Media & Documents','media'); ?>
<section class="admin-card"><h2>Upload files</h2><p class="hint">Files stay private until attached to published content. Maximum <?=round(content_upload_limit()/1048576,1)?> MB per file; <?=e((string)ini_get('post_max_size'))?> combined limit.</p>
<form method="post" enctype="multipart/form-data" class="admin-form editor-form" data-upload-form data-max-bytes="<?=content_upload_limit()?>" data-post-bytes="<?=ini_bytes((string)ini_get('post_max_size'))?>"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="upload_media"><label class="upload-drop">Select or drop files<input type="file" name="files[]" accept=".jpg,.jpeg,.png,.webp,.pdf,.docx,.xlsx,.pptx,.mp4,.webm" multiple required><small>Up to 10 files. For large videos, add a hosted link in Create Content.</small></label><label>Image description (optional)<input name="alt_text" maxlength="255"></label><div data-upload-feedback class="upload-feedback" aria-live="polite"></div><progress data-upload-progress max="100" value="0" hidden></progress><button class="admin-button">Upload files</button></form></section>
<section class="admin-card"><h2>Your library</h2><form method="get" class="toolbar"><input type="hidden" name="section" value="media"><input type="search" name="q" value="<?=e($search)?>" placeholder="Search filenames and descriptions" aria-label="Search media"><select name="kind" aria-label="File type"><option value="">All file types</option><?php foreach(['image'=>'Images','document'=>'Documents','video'=>'Videos'] as $key=>$label):?><option value="<?=$key?>" <?=$kind===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select><button class="admin-button">Search</button></form><p class="hint">Showing up to 100 matches. Narrow your search to find older files.</p><div class="file-list">
<?php foreach($library as $media):$kind=media_kind($media['mime_type']);?><article class="file-card">
<?php if($kind==='image'):?><img class="media-thumbnail" src="../file.php?id=<?=$media['id']?>" alt="<?=e($media['alt_text'])?>" loading="lazy"><?php else:?><span class="media-type"><?=e(strtoupper(pathinfo($media['original_name'],PATHINFO_EXTENSION)))?></span><?php endif;?>
<b><?=e($media['original_name'])?></b><small><?=number_format($media['file_size']/1048576,2)?> MB &middot; <?=e($kind)?></small><p><a class="admin-link" href="../file.php?id=<?=$media['id']?>" target="_blank" rel="noopener">Preview / download</a></p><a class="admin-link" href="index.php?section=media&amp;file=<?=$media['id']?>#file-detail">Manage / version history</a></article><?php endforeach;?>
<?php if(!$library):?><p>No files match your search.</p><?php endif;?></div></section>
<?php if(!empty($_GET['file'])):$media=editable_media((int)$_GET['file']);$references=media_references($media);$q=db()->prepare('SELECT v.*,u.name FROM media_versions v JOIN users u ON u.id=v.uploaded_by WHERE v.media_id=? ORDER BY v.id DESC');$q->execute([$media['id']]);$versions=$q->fetchAll();?>
<section class="admin-card" id="file-detail"><h2><?=e($media['original_name'])?></h2><h3>Used by</h3><ul><?php foreach($references as $reference):?><li><a href="index.php?section=<?=$reference['deleted_at']?'trash':'editor&id='.$reference['id']?>"><?=e($reference['title'])?></a> &middot; <?=e($reference['deleted_at']?'in Trash':$reference['status'])?></li><?php endforeach;?></ul><?php if(!$references):?><p class="hint">Not currently attached to any content.</p><?php endif;?>
<h3>Replace file</h3><p class="hint">The public link stays the same. Attached posts use the newest version, and previous versions remain available only to authorised staff.</p><form method="post" enctype="multipart/form-data" class="admin-form editor-form" data-upload-form data-max-bytes="<?=content_upload_limit()?>"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="replace_media"><input type="hidden" name="media_id" value="<?=$media['id']?>"><label class="upload-drop">New version<input type="file" name="file" required></label><div data-upload-feedback aria-live="polite"></div><progress data-upload-progress max="100" value="0" hidden></progress><button class="admin-button">Upload replacement</button></form>
<h3>Version history</h3><?php foreach($versions as $version):?><p><a href="../file.php?id=<?=$media['id']?>&amp;version=<?=$version['id']?>" target="_blank" rel="noopener"><?=e($version['original_name'])?></a> &middot; <?=e($version['created_at'])?> &middot; <?=e($version['name'])?></p><?php endforeach;?><?php if(!$versions):?><p class="hint">Original upload. A version history will be created when this file is replaced.</p><?php endif;?>
<?php if($user['role']!=='contributor'):?><form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="trash_media"><input type="hidden" name="id" value="<?=$media['id']?>"><label class="checkbox-label"><input type="checkbox" name="confirm_delete" value="1" required <?=$references?'disabled':''?>>Move this unused file to Trash</label><button class="admin-button danger-button" <?=$references?'disabled':''?>>Move to Trash</button><?php if($references):?><p class="hint">Detach this file from all listed content, including Trash items, before deleting it.</p><?php endif;?></form><?php endif;?></section>
<?php endif;admin_footer();return;}

if($section==='trash'){
    require_role(['administrator','editor']);admin_header('Trash & Restore','trash');
    $contents=db()->query('SELECT c.id,c.title,s.deleted_at FROM content c JOIN content_state s ON s.content_id=c.id WHERE s.deleted_at IS NOT NULL ORDER BY s.deleted_at DESC')->fetchAll();
    $files=db()->query('SELECT m.id,m.original_name,s.deleted_at FROM media m JOIN media_state s ON s.media_id=m.id WHERE s.deleted_at IS NOT NULL ORDER BY s.deleted_at DESC')->fetchAll(); ?>
<section class="admin-card"><h2>Recover deleted items</h2><p>Content is restored as a draft so it can be checked before publishing. Nothing in Trash is automatically erased.</p>
<?php foreach(['content'=>$contents,'media'=>$files] as $kind=>$records):?><h3><?=$kind==='content'?'Content':'Files'?></h3><?php if(!$records):?><p class="hint">No items in this section.</p><?php endif;?><?php foreach($records as $record):?><div class="trash-row"><div><b><?=e($record['title']??$record['original_name'])?></b><p class="hint">Moved to Trash <?=e($record['deleted_at'])?></p></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="restore_<?=$kind?>"><input type="hidden" name="id" value="<?=$record['id']?>"><button class="admin-button">Restore</button></form></div><?php endforeach;endforeach;?></section>
<?php admin_footer();return;}

if($section==='security'){
    $record=security_record((int)$user['id']);$pending=$_SESSION['totp_enrolment']??null;if($pending && time()-$pending['started']>600){unset($_SESSION['totp_enrolment']);$pending=null;}
    $recovery=$_SESSION['recovery_codes_display']??[];unset($_SESSION['recovery_codes_display']);admin_header('My Security','security'); ?>
<section class="admin-card"><h2>Two-factor authentication</h2><p>Requires your password and an authenticator code at login. Status: <b><?=$record['totp_secret']?'Enabled':'Not enabled'?></b>.</p>
<?php if($recovery):?><div class="admin-alert success"><b>Save these recovery codes somewhere private. They are shown only once.</b><p>Each code can be used once if you lose access to your authenticator.</p><pre><?=e(implode("\n",$recovery))?></pre></div><?php endif;?>
<?php if(!$record['totp_secret'] && !$pending):?><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="begin_2fa"><label>Your current password<input type="password" name="current_password" required autocomplete="current-password"></label><button class="admin-button">Set up authenticator</button></form>
<?php elseif($pending):?><p>In your authenticator app, choose “Enter a setup key”. Use account <?=e($user['email'])?>, issuer AIDA, a time-based code, SHA-1, 6 digits and 30 seconds.</p><label class="secret-key">Setup key <code><?=e($pending['secret'])?></code></label><p class="hint">Do not share this key. Setup expires after 10 minutes. No external QR service receives your secret.</p><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="confirm_2fa"><label>Your current password<input type="password" name="current_password" required autocomplete="current-password"></label><label>Code from your authenticator<input name="code" pattern="[0-9]{6}" maxlength="6" inputmode="numeric" autocomplete="one-time-code" required></label><button class="admin-button">Confirm &amp; enable</button></form>
<?php else:?><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="disable_2fa"><label>Your current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>Fresh authenticator or recovery code<input name="code" autocomplete="one-time-code" required></label><button class="admin-button danger-button">Disable two-factor authentication</button></form><?php endif;?></section>
<section class="admin-card"><h2>Change password</h2><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="change_password"><label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="new_password" autocomplete="new-password" minlength="12" maxlength="72" required></label><label>Confirm new password<input type="password" name="confirm_password" autocomplete="new-password" required></label><?php if($record['totp_secret']):?><label>Fresh authenticator or recovery code<input name="code" autocomplete="one-time-code" required></label><?php endif;?><button class="admin-button">Change password</button></form></section>
<section class="admin-card"><h2>Sign out other sessions</h2><p>Use this if you signed in on another device or suspect unwanted access. Sessions also expire after 30 minutes of inactivity or 12 hours total.</p><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="revoke_others"><label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><?php if($record['totp_secret']):?><label>Fresh authenticator or recovery code<input name="code" autocomplete="one-time-code" required></label><?php endif;?><button class="admin-button">Sign out other devices</button></form></section>
<?php admin_footer();return;}

if($section==='activity'){
    require_role(['administrator','editor']);$q=db()->query('SELECT a.*,u.name FROM audit_logs a JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 200');admin_header('Activity Log','activity'); ?>
<section class="admin-card"><p class="hint">Latest 200 successful staff actions. Failed login attempts are recorded separately for throttling.</p><table class="data-table"><tr><th>When</th><th>Who</th><th>Action</th><th>Item</th><th>IP address</th></tr><?php foreach($q as $entry):?><tr><td><?=e($entry['created_at'])?></td><td><?=e($entry['name'])?></td><td><?=e(str_replace('_',' ',$entry['action']))?></td><td><?=e($entry['entity_type'])?> #<?=e((string)$entry['entity_id'])?></td><td><?=e($entry['ip_address'])?></td></tr><?php endforeach;?></table></section>
<?php admin_footer();return;}

if($section==='backups'){
    require_role(['administrator']);require_once __DIR__.'/backups.php';$backups=backup_list();admin_header('Backups','backups'); ?>
<section class="admin-card"><h2>Database and uploaded files</h2><p>Create a private ZIP backup containing the database and all library file versions. Backups contain private applications and account data: store downloaded copies securely.</p><p class="hint">Automatic scheduling must be enabled in Hostinger. See BACKEND-UPGRADE.md for the cron command and tested restore procedure. The application key must be saved separately; it is deliberately excluded from backups.</p><form method="post" class="admin-form" action="backup.php"><input type="hidden" name="csrf" value="<?=csrf()?>"><label>Your current password<input type="password" name="current_password" autocomplete="current-password" required></label><?php if(security_record((int)$user['id'])['totp_secret']):?><label>Fresh authenticator or recovery code<input name="code" autocomplete="one-time-code" required></label><?php endif;?><button class="admin-button">Create backup</button></form></section>
<section class="admin-card"><h2>Available backups</h2><?php foreach($backups as $backup):?><p><a href="backup.php?name=<?=e(rawurlencode($backup['name']))?>"><?=e($backup['name'])?></a> &middot; <?=number_format($backup['size']/1048576,2)?> MB</p><?php endforeach;?><?php if(!$backups):?><p>No backups yet.</p><?php endif;?></section>
<?php admin_footer();return;}
