<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';
require_once __DIR__ . '/../app/admin-actions.php';
require_once __DIR__ . '/../app/security-actions.php';
require_login();

$types=['insight'=>'Insights & News','publication'=>'Publications','project'=>'Projects & Impact','event'=>'Events & Videos','governance'=>'Governance Documents'];
$section=$_GET['section'] ?? 'dashboard';
if (!is_string($section) || !in_array($section,['dashboard','content','editor','delete','media','trash','security','activity','backups','messages','applications','settings','users'],true)) $section='dashboard';
$user=current_user();

if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (empty($_POST) && (int)($_SERVER['CONTENT_LENGTH']??0)>0) {
        flash('error','The attachments exceed the server upload limit. Please select smaller files.');
        header('Location: index.php?section=editor'); exit;
    }
    verify_csrf(); $action=$_POST['action'] ?? '';
    backend_actions((string)$action);
    security_actions((string)$action);
    if ($action==='review_application') {
        require_role(['administrator','editor']);
        $status=$_POST['status']??'';
        if(is_string($status) && in_array($status,['new','reviewing','accepted','declined'],true)) {
            $id=(int)($_POST['id']??0);
            db()->prepare('UPDATE applications SET status=? WHERE id=?')->execute([$status,$id]);
            audit('review','application',$id);
            flash('success','Application status updated.');
        }
        header('Location: index.php?section=applications'); exit;
    }
    if ($action==='save_settings') { require_role(['administrator']); foreach(['hero_title','hero_text','contact_email','contact_phone','contact_address'] as $key){$stmt=db()->prepare('INSERT INTO site_settings (setting_key,setting_value,updated_by) VALUES (?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)');$stmt->execute([$key,trim($_POST[$key]??''),$user['id']]);} audit('update','settings');flash('success','Website settings updated.');header('Location: index.php?section=settings');exit; }
    if ($action==='create_user') { require_role(['administrator']);$name=trim($_POST['name']??'');$email=filter_var(trim($_POST['email']??''),FILTER_VALIDATE_EMAIL);$password=$_POST['password']??'';$role=$_POST['role']??'contributor';if(!$name||!$email||(strlen($password)<12||strlen($password)>72)||!in_array($role,['administrator','editor','contributor'],true)){flash('error','Use a name, valid email, role, and password between 12 and 72 bytes.');}else{try{db()->prepare('INSERT INTO users(name,email,password_hash,role)VALUES(?,?,?,?)')->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]);audit('create','user',(int)db()->lastInsertId());flash('success','Team account created.');}catch(PDOException $e){flash('error','That email address is already in use.');}}header('Location: index.php?section=users');exit; }
}
function admin_header(string $title,string $section): void { global $user; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($title) ?> | AIDA Portal</title><link rel="stylesheet" href="../assets/css/admin.css"></head><body><div class="admin-shell"><aside class="admin-side"><a class="brand" href="../index.php"><img src="../Logo.png" alt="AIDA"></a><nav><a class="<?= $section==='dashboard'?'active':'' ?>" href="index.php">Overview</a><a class="<?= in_array($section,['content','editor'],true)?'active':'' ?>" href="index.php?section=content">Content</a><a class="<?= $section==='media'?'active':'' ?>" href="index.php?section=media">Media & Documents</a><?php if(in_array($user['role'],['administrator','editor'],true)): ?><a class="<?= $section==='messages'?'active':'' ?>" href="index.php?section=messages">Messages</a><a class="<?= $section==='applications'?'active':'' ?>" href="index.php?section=applications">Applications</a><?php endif; ?><?php if($user['role']==='administrator'): ?><a class="<?= $section==='settings'?'active':'' ?>" href="index.php?section=settings">Home Page</a><a class="<?= $section==='users'?'active':'' ?>" href="index.php?section=users">Team Access</a><?php endif; ?><a href="index.php?section=security">My Security</a><?php if($user['role']!=='contributor'):?><a href="index.php?section=trash">Trash &amp; Restore</a><a href="index.php?section=activity">Activity Log</a><?php endif;?><?php if($user['role']==='administrator'):?><a href="index.php?section=backups">Backups</a><?php endif;?></nav><form method="post" action="logout.php"><input type="hidden" name="csrf" value="<?=csrf()?>"><button class="signout signout-button">Sign out</button></form></aside><main class="admin-main"><header class="admin-top"><div><h1><?= e($title) ?></h1><p>Manage AIDA’s public website.</p></div><span class="user-pill"><?= e($user['name']) ?> · <?= e(ucfirst($user['role'])) ?></span></header><?php if($m=flash('success')):?><div class="admin-alert success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="admin-alert error"><?=e($m)?></div><?php endif;?>
<?php }
function admin_footer(): void { echo '<script src="../assets/js/admin.js" defer></script></main></div></body></html>'; }

if (in_array($section,['editor','media','trash','security','activity','backups'],true)) { require __DIR__.'/../app/admin-pages.php'; exit; }

if ($section==='dashboard') { require_role(['administrator','editor','contributor']); $counts=[];foreach(['insight','publication','project','event'] as $t){$q=db()->prepare('SELECT COUNT(*) FROM content WHERE NOT EXISTS (SELECT 1 FROM content_state t WHERE t.content_id=content.id AND t.deleted_at IS NOT NULL) AND content_type=?'.($user['role']==='contributor'?' AND author_id='.(int)$user['id']:''));$q->execute([$t]);$counts[$t]=$q->fetchColumn();}$recent=db()->query('SELECT c.*,u.name author FROM content c JOIN users u ON u.id=c.author_id WHERE NOT EXISTS (SELECT 1 FROM content_state t WHERE t.content_id=c.id AND t.deleted_at IS NOT NULL)'.($user['role']==='contributor'?' AND c.author_id='.(int)$user['id']:'').' ORDER BY c.updated_at DESC LIMIT 7')->fetchAll();admin_header('Overview','dashboard'); ?>
<div class="metric-grid"><?php foreach(['insight'=>'Insights','publication'=>'Publications','project'=>'Projects','event'=>'Events'] as $k=>$label):?><div class="metric"><b><?= $counts[$k] ?></b><span><?=e($label)?></span></div><?php endforeach;?></div><section class="admin-card"><div class="admin-card-header"><h2>Recent updates</h2><a class="admin-link" href="index.php?section=editor">+ Create content</a></div><table class="data-table"><tr><th>Title</th><th>Type</th><th>Status</th><th>Updated</th></tr><?php foreach($recent as $item):?><tr><td><a href="index.php?section=editor&id=<?=$item['id']?>"><?=e($item['title'])?></a></td><td><?=e($types[$item['content_type']])?></td><td><span class="badge <?=e($item['status'])?>"><?=e($item['status'])?></span></td><td><?=e(date('d M Y',strtotime($item['updated_at'])))?></td></tr><?php endforeach;?></table></section><?php admin_footer(); exit; }

if ($section==='content') { $type=$_GET['type']??'';$sql='SELECT c.*,u.name author FROM content c JOIN users u ON u.id=c.author_id WHERE NOT EXISTS (SELECT 1 FROM content_state t WHERE t.content_id=c.id AND t.deleted_at IS NOT NULL)';$params=[];if(isset($types[$type])){$sql.=' AND content_type=?';$params[]=$type;}if($user['role']==='contributor'){$sql.=' AND c.author_id=?';$params[]=$user['id'];}$sql.=' ORDER BY c.updated_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$items=$stmt->fetchAll();admin_header('Content','content');?>
<div class="toolbar"><form method="get"><input type="hidden" name="section" value="content"><select name="type" onchange="this.form.submit()"><option value="">All content</option><?php foreach($types as $key=>$label):?><option value="<?=$key?>" <?=$type===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></form><a class="admin-button" href="index.php?section=editor">Create content →</a></div><section class="admin-card"><table class="data-table"><tr><th>Title</th><th>Type</th><th>Author</th><th>Status</th><th></th></tr><?php foreach($items as $item):?><tr><td><?=e($item['title'])?></td><td><?=e($types[$item['content_type']])?></td><td><?=e($item['author'])?></td><td><span class="badge <?=e($item['status'])?>"><?=e($item['status'])?></span></td><td><a class="admin-link" href="index.php?section=editor&id=<?=$item['id']?>">Edit →</a><?php if(in_array($user['role'],['administrator','editor'],true)): ?> <a class="delete-link" href="index.php?section=delete&id=<?=$item['id']?>">Move to Trash</a><?php endif; ?></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }

if ($section==='delete') {
    require_role(['administrator','editor']);
    $q=db()->prepare('SELECT id,title FROM content WHERE id=? AND NOT EXISTS (SELECT 1 FROM content_state t WHERE t.content_id=content.id AND t.deleted_at IS NOT NULL)'); $q->execute([(int)($_GET['id']??0)]); $record=$q->fetch();
    if (!$record) { http_response_code(404); exit('Content item not found.'); }
    admin_header('Delete content','content'); ?>
<section class="admin-card"><h2>Delete <?=e($record['title'])?>?</h2><p>This moves the write-up to Trash and removes it from the public website. You can restore it later. Its attachments and homepage setting are preserved.</p>
<form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_content"><input type="hidden" name="id" value="<?=$record['id']?>">
<label class="checkbox-label"><input type="checkbox" name="confirm_delete" value="1" required> Move this content to Trash. It can be restored later.</label>
<div class="content-controls"><button class="admin-button danger-button">Move to Trash</button><a class="admin-link" href="index.php?section=content">Cancel</a></div></form></section>
<?php admin_footer();exit; }

if ($section==='messages') { require_role(['administrator','editor']);$messages=db()->query('SELECT * FROM contact_messages ORDER BY created_at DESC LIMIT 100')->fetchAll();admin_header('Contact Messages','messages');?>
<section class="admin-card"><p class="hint">Messages submitted from the public AIDA contact form.</p><table class="data-table"><tr><th>From</th><th>Message</th><th>Received</th></tr><?php foreach($messages as $message):?><tr><td><b><?=e($message['name'])?></b><br><a href="mailto:<?=e($message['email'])?>"><?=e($message['email'])?></a></td><td><?=nl2br(e($message['message']))?></td><td><?=e(date('d M Y H:i',strtotime($message['created_at'])))?></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }

if ($section==='settings') { require_role(['administrator']);$settings=db()->query('SELECT setting_key,setting_value FROM site_settings')->fetchAll(PDO::FETCH_KEY_PAIR);admin_header('Home Page','settings');?>
<section class="admin-card"><h2>Homepage content</h2><form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_settings"><label>Hero title<input name="hero_title" value="<?=e($settings['hero_title']??'')?>"></label><label>Hero introduction<textarea name="hero_text" rows="4"><?=e($settings['hero_text']??'')?></textarea></label><div class="form-grid"><label>Email address<input type="email" name="contact_email" value="<?=e($settings['contact_email']??'')?>"></label><label>Phone number<input name="contact_phone" value="<?=e($settings['contact_phone']??'')?>"></label><label class="full">Office address<textarea name="contact_address" rows="3"><?=e($settings['contact_address']??'')?></textarea></label></div><button class="admin-button">Save homepage settings →</button></form></section><?php admin_footer();exit; }

if ($section==='users') { require_role(['administrator']);$users=db()->query('SELECT id,name,email,role,is_active,last_login_at,created_at FROM users ORDER BY created_at DESC')->fetchAll();admin_header('Team Access','users');?>
<section class="admin-card"><h2>Add a team member</h2><form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create_user"><div class="form-grid"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Role<select name="role"><option value="contributor">Contributor — drafts only</option><option value="editor">Editor — can publish</option><option value="administrator">Administrator — full access</option></select></label><label>Password <small>At least 12 characters</small><input type="password" name="password" minlength="12" maxlength="72" required></label></div><button class="admin-button">Create account →</button></form></section><section class="admin-card"><h2>Current access</h2><table class="data-table"><tr><th>Name</th><th>Email</th><th>Role</th><th>Last sign in</th><th>Manage access</th></tr><?php foreach($users as $member):?><tr><td><?=e($member['name'])?></td><td><?=e($member['email'])?></td><td><span class="badge"><?=e($member['role'])?></span></td><td><?=e($member['last_login_at']?date('d M Y',strtotime($member['last_login_at'])):'Not yet')?><br><?= $member['is_active']?'Active':'Disabled'?></td><td><?php if((int)$member['id']!==(int)$user['id']):?><details><summary>Manage access</summary><form method="post" class="admin-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="id" value="<?=$member['id']?>"><label>Your current password<input type="password" name="current_password" autocomplete="current-password" required></label><?php if(security_record((int)$user['id'])['totp_secret']):?><label>Fresh authenticator or recovery code<input name="code" autocomplete="one-time-code" required></label><?php endif;?><label>New password (only for reset)<input type="password" name="new_password" minlength="12" maxlength="72" autocomplete="new-password"></label><button class="admin-button" name="action" value="toggle_user"><?=$member['is_active']?'Disable account':'Enable account'?></button><button class="admin-button" name="action" value="revoke_sessions">Sign out all sessions</button><button class="admin-button" name="action" value="reset_password">Reset password</button></form></details><?php else:?>Your account<?php endif;?></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }

if ($section==='applications') {
    require_role(['administrator','editor']);
    $applications=[];try{$applications=db()->query('SELECT * FROM applications ORDER BY created_at DESC LIMIT 100')->fetchAll();}catch(Throwable $error){error_log('AIDA applications: '.$error->getMessage());flash('error','Applications could not be loaded. Please check the database upgrade and private error log.');}
    admin_header('Applications','applications'); ?>
<section class="admin-card"><h2>People interested in joining AIDA</h2><p class="hint">Review applications and record a decision. Status changes do not send emails; contact applicants separately.</p>
<?php if (!$applications): ?><p>No applications have been received yet.</p><?php endif; ?>
<?php foreach($applications as $application): ?><details class="application-record"><summary><b><?=e($application['name'])?></b> · <?=e($application['interest'])?> <span class="badge"><?=e($application['status'])?></span></summary>
<p><b>Email:</b> <a href="mailto:<?=e($application['email'])?>"><?=e($application['email'])?></a><br><b>Phone:</b> <?=e($application['phone'])?><br><b>Location:</b> <?=e($application['location'])?><br><b>Organisation:</b> <?=e($application['organisation'])?><br><b>Received:</b> <?=e($application['created_at'])?></p>
<h3>Skills and experience</h3><p><?=nl2br(e($application['expertise']))?></p><h3>Reason for joining</h3><p><?=nl2br(e($application['motivation']))?></p>
<form method="post" class="application-review"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="review_application"><input type="hidden" name="id" value="<?=$application['id']?>"><label>Status <select name="status"><?php foreach(['new','reviewing','accepted','declined'] as $s): ?><option value="<?=$s?>" <?=$application['status']===$s?'selected':''?>><?=ucfirst($s)?></option><?php endforeach; ?></select></label><button class="admin-button">Save status</button></form></details><?php endforeach; ?></section>
<?php admin_footer(); exit; }

