<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';
require_login();

$types=['insight'=>'Insights & News','publication'=>'Publications','project'=>'Projects & Impact','event'=>'Events & Videos','governance'=>'Governance Documents'];
$section=$_GET['section'] ?? 'dashboard';
if (!in_array($section,['dashboard','content','editor','media','messages','settings','users'],true)) $section='dashboard';
$user=current_user();

if ($_SERVER['REQUEST_METHOD']==='POST') {
    verify_csrf(); $action=$_POST['action'] ?? '';
    if ($action==='save_content') {
        require_role(['administrator','editor','contributor']);
        $id=(int)($_POST['id']??0); $type=$_POST['content_type']??'insight'; $title=trim($_POST['title']??''); $status=$_POST['status']??'draft';
        if (!$title || !isset($types[$type])) { flash('error','Add a title and content type.'); header('Location: index.php?section=editor'.($id?'&id='.$id:'')); exit; }
        if ($user['role']==='contributor' && $status==='published') $status='review';
        if (!in_array($status,['draft','review','published','archived'],true)) $status='draft';
        $slug=slugify($_POST['slug']?:$title); $data=[$type,$title,$slug,trim($_POST['summary']??''),trim($_POST['body']??''),$status,trim($_POST['featured_image']??''),trim($_POST['document_path']??''),trim($_POST['video_url']??'') ?: null,($_POST['event_date']??'') ?: null];
        if ($id) {
            $where='id=?'; $params=[$id]; if ($user['role']==='contributor') {$where.=' AND author_id=?';$params[]=$user['id'];}
            $stmt=db()->prepare("UPDATE content SET content_type=?,title=?,slug=?,summary=?,body=?,status=?,featured_image=?,document_path=?,video_url=?,event_date=?,published_at=IF(?='published',COALESCE(published_at,NOW()),NULL) WHERE $where");
            $stmt->execute([...$data,$status,...$params]); audit('update','content',$id); flash('success','Content saved successfully.');
        } else {
            $stmt=db()->prepare("INSERT INTO content (content_type,title,slug,summary,body,status,featured_image,document_path,video_url,event_date,author_id,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,IF(?='published',NOW(),NULL))");
            $stmt->execute([...$data,$user['id'],$status]); $id=(int)db()->lastInsertId(); audit('create','content',$id); flash('success','Content created successfully.');
        }
        header('Location: index.php?section=content&type='.urlencode($type)); exit;
    }
    if ($action==='upload_media') {
        require_role(['administrator','editor','contributor']);
        $file=$_FILES['file']??null; $allowed=['image/jpeg','image/png','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.presentationml.presentation'];
        global $config; $max=($config['upload_max_mb']??25)*1024*1024;
        if (!$file || $file['error']!==UPLOAD_ERR_OK || $file['size']>$max) { flash('error','Upload failed. Use a permitted file under '.($config['upload_max_mb']??25).' MB.'); }
        else { $mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']); if(!in_array($mime,$allowed,true)){flash('error','That file type is not allowed.');} else { $dir=__DIR__.'/../uploads/'.date('Y/m'); if(!is_dir($dir))mkdir($dir,0750,true); $extension=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));$stored=bin2hex(random_bytes(16)).'.'.$extension; if(move_uploaded_file($file['tmp_name'],$dir.'/'.$stored)){ $path='uploads/'.date('Y/m').'/'.$stored; db()->prepare('INSERT INTO media (original_name,stored_name,mime_type,file_size,alt_text,uploaded_by) VALUES (?,?,?,?,?,?)')->execute([$file['name'],$path,$mime,$file['size'],trim($_POST['alt_text']??''),$user['id']]);audit('upload','media',(int)db()->lastInsertId());flash('success','File uploaded. Copy its path into a content item when needed.');}else{flash('error','The server could not store that file.');} } }
        header('Location: index.php?section=media'); exit;
    }
    if ($action==='save_settings') { require_role(['administrator']); foreach(['hero_title','hero_text','contact_email','contact_phone','contact_address'] as $key){$stmt=db()->prepare('INSERT INTO site_settings (setting_key,setting_value,updated_by) VALUES (?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_by=VALUES(updated_by)');$stmt->execute([$key,trim($_POST[$key]??''),$user['id']]);} audit('update','settings');flash('success','Website settings updated.');header('Location: index.php?section=settings');exit; }
    if ($action==='create_user') { require_role(['administrator']);$name=trim($_POST['name']??'');$email=filter_var(trim($_POST['email']??''),FILTER_VALIDATE_EMAIL);$password=$_POST['password']??'';$role=$_POST['role']??'contributor';if(!$name||!$email||strlen($password)<12||!in_array($role,['administrator','editor','contributor'],true)){flash('error','Use a name, valid email, role, and password of at least 12 characters.');}else{try{db()->prepare('INSERT INTO users(name,email,password_hash,role)VALUES(?,?,?,?)')->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]);audit('create','user',(int)db()->lastInsertId());flash('success','Team account created.');}catch(PDOException $e){flash('error','That email address is already in use.');}}header('Location: index.php?section=users');exit; }
}
function admin_header(string $title,string $section): void { global $user; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($title) ?> | AIDA Portal</title><link rel="stylesheet" href="../assets/css/admin.css"></head><body><div class="admin-shell"><aside class="admin-side"><a class="brand" href="../index.php"><img src="../Logo.png" alt="AIDA"></a><nav><a class="<?= $section==='dashboard'?'active':'' ?>" href="index.php">Overview</a><a class="<?= in_array($section,['content','editor'],true)?'active':'' ?>" href="index.php?section=content">Content</a><a class="<?= $section==='media'?'active':'' ?>" href="index.php?section=media">Media & Documents</a><a class="<?= $section==='messages'?'active':'' ?>" href="index.php?section=messages">Messages</a><?php if($user['role']==='administrator'): ?><a class="<?= $section==='settings'?'active':'' ?>" href="index.php?section=settings">Home Page</a><a class="<?= $section==='users'?'active':'' ?>" href="index.php?section=users">Team Access</a><?php endif; ?></nav><a class="signout" href="logout.php">Sign out</a></aside><main class="admin-main"><header class="admin-top"><div><h1><?= e($title) ?></h1><p>Manage AIDA’s public website.</p></div><span class="user-pill"><?= e($user['name']) ?> · <?= e(ucfirst($user['role'])) ?></span></header><?php if($m=flash('success')):?><div class="admin-alert success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="admin-alert error"><?=e($m)?></div><?php endif;?>
<?php }
function admin_footer(): void { echo '</main></div></body></html>'; }

if ($section==='dashboard') { require_role(['administrator','editor','contributor']); $counts=[];foreach(['insight','publication','project','event'] as $t){$q=db()->prepare('SELECT COUNT(*) FROM content WHERE content_type=?'.($user['role']==='contributor'?' AND author_id='.(int)$user['id']:''));$q->execute([$t]);$counts[$t]=$q->fetchColumn();}$recent=db()->query('SELECT c.*,u.name author FROM content c JOIN users u ON u.id=c.author_id ORDER BY c.updated_at DESC LIMIT 7')->fetchAll();admin_header('Overview','dashboard'); ?>
<div class="metric-grid"><?php foreach(['insight'=>'Insights','publication'=>'Publications','project'=>'Projects','event'=>'Events'] as $k=>$label):?><div class="metric"><b><?= $counts[$k] ?></b><span><?=e($label)?></span></div><?php endforeach;?></div><section class="admin-card"><div class="admin-card-header"><h2>Recent updates</h2><a class="admin-link" href="index.php?section=editor">+ Create content</a></div><table class="data-table"><tr><th>Title</th><th>Type</th><th>Status</th><th>Updated</th></tr><?php foreach($recent as $item):?><tr><td><a href="index.php?section=editor&id=<?=$item['id']?>"><?=e($item['title'])?></a></td><td><?=e($types[$item['content_type']])?></td><td><span class="badge <?=e($item['status'])?>"><?=e($item['status'])?></span></td><td><?=e(date('d M Y',strtotime($item['updated_at'])))?></td></tr><?php endforeach;?></table></section><?php admin_footer(); exit; }

if ($section==='content') { $type=$_GET['type']??'';$sql='SELECT c.*,u.name author FROM content c JOIN users u ON u.id=c.author_id WHERE 1';$params=[];if(isset($types[$type])){$sql.=' AND content_type=?';$params[]=$type;}if($user['role']==='contributor'){$sql.=' AND c.author_id=?';$params[]=$user['id'];}$sql.=' ORDER BY c.updated_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$items=$stmt->fetchAll();admin_header('Content','content');?>
<div class="toolbar"><form method="get"><input type="hidden" name="section" value="content"><select name="type" onchange="this.form.submit()"><option value="">All content</option><?php foreach($types as $key=>$label):?><option value="<?=$key?>" <?=$type===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></form><a class="admin-button" href="index.php?section=editor">Create content →</a></div><section class="admin-card"><table class="data-table"><tr><th>Title</th><th>Type</th><th>Author</th><th>Status</th><th></th></tr><?php foreach($items as $item):?><tr><td><?=e($item['title'])?></td><td><?=e($types[$item['content_type']])?></td><td><?=e($item['author'])?></td><td><span class="badge <?=e($item['status'])?>"><?=e($item['status'])?></span></td><td><a class="admin-link" href="index.php?section=editor&id=<?=$item['id']?>">Edit →</a></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }

if ($section==='editor') { $item=['id'=>'','content_type'=>'insight','title'=>'','slug'=>'','summary'=>'','body'=>'','status'=>'draft','featured_image'=>'','document_path'=>'','video_url'=>'','event_date'=>''];if(!empty($_GET['id'])){$stmt=db()->prepare('SELECT * FROM content WHERE id=?'.($user['role']==='contributor'?' AND author_id=?':''));$stmt->execute($user['role']==='contributor'?[(int)$_GET['id'],$user['id']]:[(int)$_GET['id']]);$item=$stmt->fetch();if(!$item){http_response_code(404);exit('Content item not found.');}}admin_header($item['id']?'Edit content':'Create content','editor');?>
<form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_content"><input type="hidden" name="id" value="<?=e((string)$item['id'])?>"><div class="editor-grid"><div><label>Title<input name="title" value="<?=e($item['title'])?>" required></label><br><label>Short summary<textarea name="summary" rows="3"><?=e($item['summary'])?></textarea></label><br><label>Write-up / content<textarea name="body"><?=e($item['body'])?></textarea></label></div><aside class="editor-side"><label>Content type<select name="content_type"><?php foreach($types as $key=>$label):?><option value="<?=$key?>" <?=$item['content_type']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label>URL label <input name="slug" value="<?=e($item['slug'])?>"><small>Leave blank to generate from title.</small></label><label>Status<select name="status"><option value="draft" <?=$item['status']==='draft'?'selected':''?>>Draft</option><option value="review" <?=$item['status']==='review'?'selected':''?>>Ready for review</option><?php if($user['role']!=='contributor'):?><option value="published" <?=$item['status']==='published'?'selected':''?>>Published</option><option value="archived" <?=$item['status']==='archived'?'selected':''?>>Archived</option><?php endif;?></select></label><label>Featured image path<input name="featured_image" value="<?=e($item['featured_image'])?>" placeholder="uploads/2026/09/file.jpg"></label><label>Document path<input name="document_path" value="<?=e($item['document_path'])?>" placeholder="uploads/2026/09/report.pdf"></label><label>Video URL<input type="url" name="video_url" value="<?=e($item['video_url'])?>" placeholder="YouTube or Vimeo link"></label><label>Event date<input type="datetime-local" name="event_date" value="<?=e($item['event_date']?date('Y-m-d\TH:i',strtotime($item['event_date'])):'')?>"></label><p class="hint">Upload files in Media & Documents, then paste the displayed file path here.</p><button class="admin-button">Save content →</button></aside></div></form><?php admin_footer();exit; }

if ($section==='media') { require_role(['administrator','editor','contributor']);$media=db()->query('SELECT m.*,u.name FROM media m JOIN users u ON u.id=m.uploaded_by ORDER BY m.created_at DESC LIMIT 60')->fetchAll();admin_header('Media & Documents','media');?>
<section class="admin-card"><h2>Upload a document or image</h2><p class="hint">Accepted: JPG, PNG, WebP, PDF, DOCX, XLSX and PPTX. Videos should be hosted on YouTube or Vimeo and added by link.</p><form method="post" enctype="multipart/form-data" class="admin-form upload-zone"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="upload_media"><label>Select file<input type="file" name="file" required></label><label>Image description / alt text <input name="alt_text"></label><button class="admin-button">Upload file →</button></form></section><section class="admin-card"><h2>Recent uploads</h2><div class="file-list"><?php foreach($media as $file):?><article class="file-card"><b><?=e($file['original_name'])?></b><small><?=e($file['mime_type'])?> · <?=number_format($file['file_size']/1024,1)?> KB</small><p class="hint"><?=e($file['stored_name'])?></p></article><?php endforeach;?></div></section><?php admin_footer();exit; }

if ($section==='messages') { require_role(['administrator','editor']);$messages=db()->query('SELECT * FROM contact_messages ORDER BY created_at DESC LIMIT 100')->fetchAll();admin_header('Contact Messages','messages');?>
<section class="admin-card"><p class="hint">Messages submitted from the public AIDA contact form.</p><table class="data-table"><tr><th>From</th><th>Message</th><th>Received</th></tr><?php foreach($messages as $message):?><tr><td><b><?=e($message['name'])?></b><br><a href="mailto:<?=e($message['email'])?>"><?=e($message['email'])?></a></td><td><?=nl2br(e($message['message']))?></td><td><?=e(date('d M Y H:i',strtotime($message['created_at'])))?></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }

if ($section==='settings') { require_role(['administrator']);$settings=db()->query('SELECT setting_key,setting_value FROM site_settings')->fetchAll(PDO::FETCH_KEY_PAIR);admin_header('Home Page','settings');?>
<section class="admin-card"><h2>Homepage content</h2><form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_settings"><label>Hero title<input name="hero_title" value="<?=e($settings['hero_title']??'')?>"></label><label>Hero introduction<textarea name="hero_text" rows="4"><?=e($settings['hero_text']??'')?></textarea></label><div class="form-grid"><label>Email address<input type="email" name="contact_email" value="<?=e($settings['contact_email']??'')?>"></label><label>Phone number<input name="contact_phone" value="<?=e($settings['contact_phone']??'')?>"></label><label class="full">Office address<textarea name="contact_address" rows="3"><?=e($settings['contact_address']??'')?></textarea></label></div><button class="admin-button">Save homepage settings →</button></form></section><?php admin_footer();exit; }

if ($section==='users') { require_role(['administrator']);$users=db()->query('SELECT id,name,email,role,is_active,last_login_at,created_at FROM users ORDER BY created_at DESC')->fetchAll();admin_header('Team Access','users');?>
<section class="admin-card"><h2>Add a team member</h2><form method="post" class="editor-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create_user"><div class="form-grid"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Role<select name="role"><option value="contributor">Contributor — drafts only</option><option value="editor">Editor — can publish</option><option value="administrator">Administrator — full access</option></select></label><label>Password <small>At least 12 characters</small><input type="password" name="password" minlength="12" required></label></div><button class="admin-button">Create account →</button></form></section><section class="admin-card"><h2>Current access</h2><table class="data-table"><tr><th>Name</th><th>Email</th><th>Role</th><th>Last sign in</th></tr><?php foreach($users as $member):?><tr><td><?=e($member['name'])?></td><td><?=e($member['email'])?></td><td><span class="badge"><?=e($member['role'])?></span></td><td><?=e($member['last_login_at']?date('d M Y',strtotime($member['last_login_at'])):'Not yet')?></td></tr><?php endforeach;?></table></section><?php admin_footer();exit; }
